server:
  port: 9081

spring:
  application:
    name: keycloak-demo

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/spring-app-realm
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: spring-app-client
            client-secret: vGAQHjL23Y0ItqRh3EOuax6mbJF4eEPD
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"


        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/spring-app-realm

jwt:
  auth:
    converter:
      resource-id: preferred_username