server:
  port: 9081

spring:
  application:
    name: keycloak-demo

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/levelup
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
      client:
        registration:
          keycloak:
            client-id: levelup-client
            client-secret: G9dxRpoxtu7I7uSmi9n57RQQzjFCkqAz
            authorization-grant-type: password
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/levelup

jwt:
  auth:
    converter:
      resource-id: preferred_username